version: '3.7'

services:
  wttddock:
    image: wttddock
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/eventy
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment: 
     - DEBUG=1